version: '3.1'

services:
  front:
    build:
      context: .
    image: front
    container_name: front
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/2025:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - iteasyopsnetwork

networks:
  iteasyopsnetwork:
    external: true

