version: '3.1'

services:
  front:
    build:
      context: .
    image: front
    container_name: front
    environment:
      - TZ=Asia/Seoul
    ports:
      - "80:80"
    networks:
      - iteasyopsnetwork

networks:
  iteasyopsnetwork:
    external: true
